
create database Yamagen;

use Yamagen;

CREATE TABLE TIPO_USUARIO(id INT PRIMARY KEY AUTO_INCREMENT, nombreTipo VARCHAR(20) NOT NULL UNIQUE);

INSERT INTO TIPO_USUARIO(nombreTipo) VALUES ('admin');

INSERT INTO TIPO_USUARIO(nombreTipo) VALUES ('usr');

CREATE TABLE ACADEMICO(id INT PRIMARY KEY AUTO_INCREMENT, nombre VARCHAR(40) NOT NULL, apellidos VARCHAR(40) NOT NULL, fotografia VARCHAR(40) NOT NULL, email VARCHAR(40) NOT NULL, centroUniAct VARCHAR(40), gradoEstudios VARCHAR(40), clave VARCHAR(20) UNIQUE);

INSERT INTO ACADEMICO(nombre, apellidos, fotografia, email, centroUniAct, gradoEstudios, clave) VALUES ("Yamagen", "Taka", "/imagenes/logo.png", "admin_yamagen@gmail.com","Black Mesa", "Ingenieria en computación", "QWERTY");

CREATE TABLE USUARIO(id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(30) UNIQUE NOT NULL, password CHAR(40) NOT NULL, id_tipo_usuario INT NOT NULL, FOREIGN KEY(id_tipo_usuario) REFERENCES TIPO_USUARIO(id), id_academico INT NOT NULL, FOREIGN KEY(id_academico) REFERENCES ACADEMICO(id));

INSERT INTO USUARIO(username, password, id_tipo_usuario, id_academico) VALUES ("AdminYamagen", "123456789", 1, 1);

CREATE TABLE LINEA_INVESTIGACION(linea VARCHAR(40) NOT NULL UNIQUE);

CREATE TABLE USR_LIN_INVES(lin_inves VARCHAR(40) NULL, FOREIGN KEY(lin_inves) REFERENCES LINEA_INVESTIGACION(linea), id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id));

CREATE TABLE LIN_INNOVADORA(id INT PRIMARY KEY AUTO_INCREMENT, nomInvestigacion VARCHAR(40) NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id));

CREATE TABLE DIRECCION(id INT PRIMARY KEY AUTO_INCREMENT, nomDireccion VARCHAR(40) NOT NULL, fechaIni DATE NOT NULL, fechaFin DATE NOT NULL, nomEmpresa VARCHAR(40) NOT NULL, nombreAlumno VARCHAR(40) NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL,  id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE ESTADIA(id INT PRIMARY KEY AUTO_INCREMENT, nomEstadia VARCHAR(40) NOT NULL, fechaIni DATE NOT NULL, fechaFin DATE NOT NULL, nomEmpresa VARCHAR(40) NOT NULL, nombreAlumno VARCHAR(40) NOT NULL,  fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE PROY_INVESTIGACION(id INT PRIMARY KEY AUTO_INCREMENT, nomProyecto VARCHAR(40) NOT NULL, fechaIni DATE NOT NULL, fechaFin DATE NOT NULL, nomEmpresa VARCHAR(40) NOT NULL,  fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE TIPO_ARTICULO(id INT PRIMARY KEY AUTO_INCREMENT, tipo VARCHAR(40) NOT NULL);

INSERT INTO TIPO_ARTICULO(tipo) VALUES ('Artículo de difusión y divulgación');

INSERT INTO TIPO_ARTICULO(tipo) VALUES ('Articulo arbitrado');

INSERT INTO TIPO_ARTICULO(tipo) VALUES ('Artículo en revista');

CREATE TABLE ARTICULO(id INT PRIMARY KEY AUTO_INCREMENT, nomArticulo VARCHAR(40) NOT NULL, nombreRevista VARCHAR(40) NOT NULL, noPaginas INT NOT NULL, isbn VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_tipo_articulo INT NOT NULL, FOREIGN KEY(id_tipo_articulo) REFERENCES TIPO_ARTICULO(id), id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE TIPO_BIBLIOGRAFICO(id INT PRIMARY KEY AUTO_INCREMENT, tipo VARCHAR(40) NOT NULL);

INSERT INTO TIPO_BIBLIOGRAFICO(tipo) VALUES ('Libro');

INSERT INTO TIPO_BIBLIOGRAFICO(tipo) VALUES ('Memorias');

CREATE TABLE BIBLIOGRAFICO(id INT PRIMARY KEY AUTO_INCREMENT, nomArticulo VARCHAR(40) NOT NULL, nombreRevista VARCHAR(40) NOT NULL, editorial VARCHAR(40) NOT NULL, noPaginas INT NOT NULL, isbn VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_tipo_biblio INT NOT NULL, FOREIGN KEY(id_tipo_biblio) REFERENCES TIPO_BIBLIOGRAFICO(id), id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE INFORME_TECNICO(id INT PRIMARY KEY AUTO_INCREMENT, nomPub VARCHAR(40) NOT NULL, dependencia VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE PROD_INNOVADORA(id INT PRIMARY KEY AUTO_INCREMENT, nomPub VARCHAR(40) NOT NULL, noRegistro VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE MANUAL_OPERACION(id INT PRIMARY KEY AUTO_INCREMENT, nomPub VARCHAR(40) NOT NULL, noRegistro VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);

CREATE TABLE PROTOTIPO(id INT PRIMARY KEY AUTO_INCREMENT, nomPub VARCHAR(40) NOT NULL, noRegistro VARCHAR(40) NOT NULL, fechaPublicacion DATE NOT NULL, fechaInsercion DATE NOT NULL, status BOOL NOT NULL, id_academico INT NOT NULL, FOREIGN KEY (id_academico) REFERENCES ACADEMICO(id) ON DELETE CASCADE);
